<?php
// Automatically Generated by TestLink Installer - Tue, 08 Apr 25 22:14:37 +0000
define('DB_TYPE', 'mysql');
define('DB_USER', 'root');
define('DB_PASS', 'pwd_root');
define('DB_HOST', '172.22.2.21');
define('DB_NAME', 'testlink');
define('DB_TABLE_PREFIX', '');
 renombrar archivo por config_db.inc